Update valide

diff --git a/valide b/valide
--- a/valide
+++ b/valide
@@ -1,29 +1,26 @@
 #!/bin/bash
-echo "Bem vindo ao validador de informações!"
+#echo "Validador de informações"
 
 #read -p  "Digite seu nome: " NAME
-#[[ $(echo $NAME | grep -E "^([[:alpha:]]|[[:space:]])+$") ]] && echo Valido || echo Invaido
+#(echo $NAME | grep -E '^([[:alpha:]]|[[:space:]])+$") ' && echo -e 'Valido' || echo -e 'Invalido'
 
-#read -p "Digite sua data de nascimento: " DATA
-#[[ $(echo $DATA | grep -E "^(3[01]|[12][0-9]|0[0-9]|[0-9])/(1[0-2]|0[1-9])/(19[0-9]{2}|20(0[0-9]|1[0-8]))$") ]] && echo Valido || echo Invalido
+#read -p "DIgite a data: " DAT
+#echo $DAT | grep -E '^(0?[1-9]|[12][0-9]|3[01])/(0?[1-9]|1[0-2])/(200[0-9]|201[0-8]|19[0-9]{2})$' && echo -e 'Valido' || echo -e 'Invalido'
 
 #read -p "Digite seu CPF: " CPF
-#[[ $(echo $CPF | grep -E "^([0-9]{3})\.([0-9]{3})\.([0-9]{3})-([0-9]{2})$") ]] && echo Valido || echo Invalido
+#echo $CPF | grep -E '^([0-9]{3})\.([0-9]{3})\.([0-9]{3})-([0-9]{2})$' && echo -e 'Valido' || echo -e 'Invalido'
 
 #read -p "Digite seu RG: " RG
-#[[ $(echo $RG | grep -E "^([0-9]{2})\.([0-9]{3})\.([0-9]{3})-([0-9])$") ]] && echo Valido || echo Invalido
+#echo $RG | grep -E '^[0-9]{1,3}(\.?[0-9]{3}){2}-?[0-9a-zA-Z]$' && echo -e 'Valido' || echo -e 'Invalido'
 
 #read -p "Digite seu telefone: " TEL
-#[[ $(echo $TEL | grep -E "^\(([0-9]{2})\)(9[0-9]{4}|[0-9]{4})-([0-9]{4})$") ]] && echo Valido || echo Invalido
+#echo $TEL | grep -E '^\(([0-9]{2})\)(9[0-9]{4}|[0-9]{4})-([0-9]{4})$' && echo -e 'Valido' || echo -e 'Invalido'
 
 #read -p  "Digite seu e-mail: " MAIL
-#[[ $(echo $MAIL | grep -E "^([[:alnum:]])+\.([[:alnum:]])+@([a-z])+\.([a-z]{3})") ]] && echo Valido || echo Invalido
+#[[ $(echo $MAIL | grep -E '^[a-z]+([._-])               $' && echo Valido || echo Invalido
  
-#read -p "Digite seu IP: " IP
-#[[ $(echo $IP | grep -E "^([0-9]|[0-9]{2}|1[0-9]{2}|2[0-5]{2})\.\1\.\1\.\1") ]] && echo Valido || echo Invalido 
-
 #read -p "Digite seu IP: " IP
 #echo $IP | grep -E "^([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\.([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])){3}"
 
 #read -p "Digite sua mascará de rede: " MASK
-[[ $(echo $MASK | grep -E "^(255\.(0|128|192|224|240|248|252)\.\1\.\1") ]] && echo Valido || echo Invalido
+#echo $MASK | grep -E "^(255\.(0|128|192|224|240|248|252)\.\1\.\1") ]] && echo Valido || echo Invalido
